/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  Max,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { SubscriptionPlanCreateNestedManyWithoutAccountsInput } from "./SubscriptionPlanCreateNestedManyWithoutAccountsInput";
import { Type } from "class-transformer";
import { ArchiveCreateNestedManyWithoutAccountsInput } from "./ArchiveCreateNestedManyWithoutAccountsInput";
import { AccountCreateNestedManyWithoutAccountsInput } from "./AccountCreateNestedManyWithoutAccountsInput";
import { AccountWhereUniqueInput } from "./AccountWhereUniqueInput";

@InputType()
class AccountCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  organizationId?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string | null;

  @ApiProperty({
    required: false,
    type: () => SubscriptionPlanCreateNestedManyWithoutAccountsInput,
  })
  @ValidateNested()
  @Type(() => SubscriptionPlanCreateNestedManyWithoutAccountsInput)
  @IsOptional()
  @Field(() => SubscriptionPlanCreateNestedManyWithoutAccountsInput, {
    nullable: true,
  })
  subscriptionPlans?: SubscriptionPlanCreateNestedManyWithoutAccountsInput;

  @ApiProperty({
    required: false,
    type: () => ArchiveCreateNestedManyWithoutAccountsInput,
  })
  @ValidateNested()
  @Type(() => ArchiveCreateNestedManyWithoutAccountsInput)
  @IsOptional()
  @Field(() => ArchiveCreateNestedManyWithoutAccountsInput, {
    nullable: true,
  })
  archives?: ArchiveCreateNestedManyWithoutAccountsInput;

  @ApiProperty({
    required: false,
    type: () => AccountCreateNestedManyWithoutAccountsInput,
  })
  @ValidateNested()
  @Type(() => AccountCreateNestedManyWithoutAccountsInput)
  @IsOptional()
  @Field(() => AccountCreateNestedManyWithoutAccountsInput, {
    nullable: true,
  })
  accounts?: AccountCreateNestedManyWithoutAccountsInput;

  @ApiProperty({
    required: false,
    type: () => AccountWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccountWhereUniqueInput)
  @IsOptional()
  @Field(() => AccountWhereUniqueInput, {
    nullable: true,
  })
  account?: AccountWhereUniqueInput | null;
}

export { AccountCreateInput as AccountCreateInput };
